language: node_js
node_js:
- 5.0.0
install:
- npm install
before_script:
- npm install -g grunt-cli
script:
- grunt travis
addons:
  sauce_connect: true
env:
  global:
  - secure: Yo9+zkOdDo4x+eetVokfNX5wtke57BIBsv5ct+rMn9hk5LdFGD7kIvF31QBHsvoaPSIQnheu3pIylvoAQj94I3sclAFlyjyH2xSvFY2TkQ41vcmi75Eje/orqG5MNbf3xwFwvCsTvON6Yyxpsq5pf57KZQHTLQoMkpbmyhInouuw7VtefPYz8VzXBz+B174+N1uWBwPW3wX6q2C9ctomu7/rNKG8aY/aLvDzyRk7KzUVJ7kUmylMe88lXRzJP6tnWclQfVIu075SWHYTRyRDNMY7zLTM0u3N49/Ks16tei87am16XzHoANoF4KAiHzZtnduQebLucSdGMG1GTyuHKiTWyax9ggJT9CjHd7xAMLz+/vfpsB3w/jZHeVRHfUT83SxXUPXjqL1vKnN/B8c5B3/9MRHH75pdBcaslBFv+QWOGRu4o8POZczf0wlkJ8vrTTGOGpwUi18vbKs4N/LbAzl3EaCMHIoWhHyNS9o8rfKp8t8aHWxeokeDrzNXH7fCpoy1H14O9C6J4hnBdDrjTSRjYptZ0FUJF9BVyzEDBRlAcE7hcSTaU0ayfM3mdML45JSPm1iHk9n2V9fFITFcQTXwbOunxmJkhoBvbfKKpVhTbR5D9TarFLz3WHlONpJuzdtEZ7NPos+aSGgCEWHB9EpIASkVzltlm5yDRQlMnWI=
  - secure: hiYrtMpUCks7g+NaraigV2U6rq+SRO+2vQ+ZtN0Ve9UFK5q37sl4QGa9qPneKAb9LmrItTPFWAIOOPSVBPTGDxOaKCLW2PbtXgdA5ubVrX1Irt7VT1A4wf26e1SevIjUeWVC6qWnAFcKQm8vbEbWB+AvB0/Zy5FAd1c0sf7AF4fqciRanvoc0wEp20vv86DtkuV/jsC5rSk0AjYcQyATrTnkCPbg+/JnByBL0Nhe9rNVaZw3JzbVJe4HftB7w0EbX9O+fUSvImLFZEvTbrzADwbFiwPVTtHKpGfkcrSLAYC9LxxQdSQGBnpCasDn1j8IAH0xrmxXKaAoB0no/y2adW34osAzSw+wWFF017h0pZVf9cYt3+cM8gVu+KRTanjGhOcy3+Kv3alDnOG+S06VgeU4zvz8zzegq/FUIQNL3ILHIemhOfX7UbIK420ciifIlB8/Fd23k2cU7ssDGW6MfyHS01ioRfzV5GXfuG2xVL6fn15bztzkIQ8gUWTZ5KTJt4P+dIHVMGmu2GnnEMXOg/aBF8pOKmm4+dOpmADrVC/T94AzUpPMfTtg3GApOUzU8xoVVboG2Zz/8Om4qfuOV4vZyfaft4PSqAmoSTRxSE2ekC2Rzdi53jybEL5As86A9FEeWUC3SFgBulzzwsD3V/O20duSoBNFxLA7BirW9H8=

notifications:
  email:
    on_success: always
    on_failure: always